package com.webox;

import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
import java.math.*; import java.time.*; import java.util.*;

@RestController @RequestMapping("/api") class Api {
 private final UserRepository users; private final DishRepository dishes; private final MenuRepository menus; private final OrderRepository orders; private final BCryptPasswordEncoder bcrypt=new BCryptPasswordEncoder();
 Api(UserRepository u,DishRepository d,MenuRepository m,OrderRepository o){users=u;dishes=d;menus=m;orders=o;}
 record Credentials(@Email @Size(max=200) String email,@Pattern(regexp="^(?=.*[A-Za-z])(?=.*\\d).{8,72}$",message="Password must contain letters and numbers and be at least 8 characters") String password){}
 record Session(String token,String role,String email){}
 @PostMapping("/auth/register") Session register(@Valid @RequestBody Credentials c){if(users.findByEmailIgnoreCase(c.email()).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Email is already registered");var u=new Domain.User();u.email=c.email().trim().toLowerCase();u.passwordHash=bcrypt.encode(c.password());u.token=UUID.randomUUID().toString();users.save(u);return new Session(u.token,u.role,u.email);}
 @PostMapping("/auth/login") Session login(@Valid @RequestBody Credentials c){var u=users.findByEmailIgnoreCase(c.email()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Incorrect email or password"));if(!bcrypt.matches(c.password(),u.passwordHash))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Incorrect email or password");u.token=UUID.randomUUID().toString();users.save(u);return new Session(u.token,u.role,u.email);}
 Domain.User me(String token){return users.findByToken(token).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Please sign in"));}
 record MenuDish(Long id,String name,String description,BigDecimal price,String category,String protein,String spice,Set<String> allergens,String image,String options,int stock){}
 @GetMapping("/menu") List<MenuDish> menu(@RequestParam(defaultValue="") @Size(max=50) String q,@RequestParam(required=false) LocalDate date){var day=date==null?LocalDate.now():date;return menus.findByMenuDateAndDishActiveTrue(day).stream().filter(m->(m.dish.name+" "+m.dish.description).toLowerCase().contains(q.toLowerCase())).map(m->new MenuDish(m.dish.id,m.dish.name,m.dish.description,m.dish.price,m.dish.category,m.dish.protein,m.dish.spice,m.dish.allergens,m.dish.image,m.dish.optionsJson,m.stock)).toList();}
 record Item(Long dishId,@Min(1) @Max(5) int quantity,@Size(max=1000) String selections,@DecimalMin("0") BigDecimal optionPrice){}
 record Place(@NotBlank @Size(max=80) String idempotencyKey,LocalDate date,@Pattern(regexp="Lunch|Dinner") String slot,@NotBlank @Size(max=200) String address,@NotEmpty List<@Valid Item> items){}
 @PostMapping("/orders") @Transactional Domain.MealOrder place(@RequestHeader("Authorization") String auth,@Valid @RequestBody Place p){var u=me(auth.replace("Bearer ",""));var old=orders.findByUserIdAndIdempotencyKey(u.id,p.idempotencyKey());if(old.isPresent())return old.get();int count=p.items().stream().mapToInt(Item::quantity).sum();if(count>5)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"An order can contain at most 5 meals");var target=nextSlot(p.date(),p.slot());if(orders.findByUserIdAndMealDateAndSlotAndActiveKey(u.id,target.date,target.slot,"ACTIVE").isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"You already have an active order for this meal");var o=new Domain.MealOrder();o.id="WB-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();o.user=u;o.mealDate=target.date;o.slot=target.slot;o.address=p.address();o.status="Pending";o.createdAt=Instant.now();o.idempotencyKey=p.idempotencyKey();o.total=BigDecimal.ZERO;for(var in:p.items()){var menu=menus.lock(target.date,in.dishId()).orElseThrow(()->new ResponseStatusException(HttpStatus.CONFLICT,"A selected dish is unavailable"));if(menu.stock<in.quantity())throw new ResponseStatusException(HttpStatus.CONFLICT,menu.dish.name+" has only "+menu.stock+" remaining");menu.stock-=in.quantity();var i=new Domain.OrderItem();i.order=o;i.dish=menu.dish;i.quantity=in.quantity();i.selections=in.selections();i.unitPrice=menu.dish.price.add(in.optionPrice()==null?BigDecimal.ZERO:in.optionPrice());i.subtotal=i.unitPrice.multiply(BigDecimal.valueOf(i.quantity));o.total=o.total.add(i.subtotal);o.items.add(i);}return orders.save(o);}
 record Slot(LocalDate date,String slot){} private Slot nextSlot(LocalDate d,String s){var now=LocalDateTime.now();var date=d==null?now.toLocalDate():d;if(date.isAfter(now.toLocalDate()))return new Slot(date,s);if("Lunch".equals(s)&&now.toLocalTime().isBefore(LocalTime.of(10,0)))return new Slot(date,s);if(now.toLocalTime().isBefore(LocalTime.of(15,0)))return new Slot(date,"Dinner");return new Slot(date.plusDays(1),"Lunch");}
 @GetMapping("/orders") List<Domain.MealOrder> orders(@RequestHeader("Authorization") String a){return orders.findByUserIdOrderByCreatedAtDesc(me(a.replace("Bearer ","")).id);}
 @PostMapping("/orders/{id}/cancel") @Transactional void cancel(@RequestHeader("Authorization") String a,@PathVariable String id){var u=me(a.replace("Bearer ",""));var o=orders.findById(id).orElseThrow();if(!o.user.id.equals(u.id))throw new ResponseStatusException(HttpStatus.FORBIDDEN);if(!o.status.equals("Pending"))throw new ResponseStatusException(HttpStatus.CONFLICT,"Only pending orders can be cancelled");o.status="Cancelled";o.activeKey=o.id;for(var i:o.items){menus.lock(o.mealDate,i.dish.id).ifPresent(m->m.stock+=i.quantity);}orders.save(o);}
}
